// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkFUm5TO2gHp2t95TVhxkUaDQ7SxbANuA',
    appId: '1:419054541843:web:a8a36d67a6dfd5dda6f3e6',
    messagingSenderId: '419054541843',
    projectId: 'chat-509ea',
    authDomain: 'chat-509ea.firebaseapp.com',
    storageBucket: 'chat-509ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZIm9c4hJ9dG5sVfVgO5fLh2NK2Ve6HMo',
    appId: '1:419054541843:android:ccc7ba43c560266fa6f3e6',
    messagingSenderId: '419054541843',
    projectId: 'chat-509ea',
    storageBucket: 'chat-509ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq6VclEtBx5OazzE5wYkgfjzSxQfKpmFo',
    appId: '1:419054541843:ios:8eb3e61ee05ba712a6f3e6',
    messagingSenderId: '419054541843',
    projectId: 'chat-509ea',
    storageBucket: 'chat-509ea.appspot.com',
    iosBundleId: 'com.example.chat',
  );
}
